name: CTD Sniper Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * 1-5' # 7:00 PM IST Mon-Fri

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread google-auth

      - name: Run Python Scanner
        env:
          GSHEET_KEY: ${{ secrets.GSHEET_KEY }} # YE LINE SABSE IMPORTANT HAI
        run: python main.py
        
